version: "3.3"
volumes:
  pg_data:

services:
  redis:
    image: redis
    restart: always

  db:
    image: postgres:14
    env_file: ./filecelery/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  filecelery:
    build: ./filecelery
    restart: always
    volumes:
      - ./filecelery:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    depends_on:
      - db

  worker:
    build: ./filecelery
    restart: always
    volumes:
      - ./filecelery:/app
    command: ["celery", "-A", "config", "worker", "-l", "info"]
    depends_on:
      - redis
