version: "3.9"

services:
  redis:
    image: redis
    restart: always

  filecelery:
    build: ./filecelery
    restart: always
    volumes:
      - ./filecelery:/app
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0:8000"]

  worker:
    build: ./filecelery
    restart: always
    volumes:
      - ./filecelery:/app
    command: ["celery", "-A", "config", "worker", "-l", "info"]
    depends_on:
      - redis
